env:
  browser: true
  es2020: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:mocha/recommended
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {}
plugins:
  - mocha
